from __future__ import annotations


REPORT_TYPES = {
    "product_master_sku",
    "product_detail_sku_daily",
    "product_detail_spu_daily",
    "trade_order_success",
    "trade_order_cancel",
    "trade_order_refund",
    "order_paid_items",
    "order_cancel_items",
    "order_refund_items",
    "aftersale_services",
    "search_rank_sku_daily",
    "sku_cost",
}


TABLE_COLUMNS: dict[str, list[tuple[str, str]]] = {
    "stores": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_name", "TEXT"),
        ("shop_id", "TEXT"),
        ("platform", "TEXT DEFAULT 'JD'"),
        ("enabled", "INTEGER DEFAULT 1"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "dim_spu": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("spu", "TEXT NOT NULL"),
        ("spu_name", "TEXT"),
        ("product_code", "TEXT"),
        ("category_level1", "TEXT"),
        ("category_level2", "TEXT"),
        ("category_level3", "TEXT"),
        ("brand", "TEXT"),
        ("status", "TEXT"),
        ("main_sku", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "dim_sku": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("sku_name", "TEXT"),
        ("merchant_sku", "TEXT"),
        ("sale_attr", "TEXT"),
        ("category_level1", "TEXT"),
        ("category_level2", "TEXT"),
        ("category_level3", "TEXT"),
        ("brand", "TEXT"),
        ("jd_price", "REAL"),
        ("stock", "INTEGER"),
        ("status", "TEXT"),
        ("product_url", "TEXT"),
        ("short_title", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "product_mapping": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("sku_name", "TEXT"),
        ("spu_name", "TEXT"),
        ("bind_status", "TEXT DEFAULT 'active'"),
        ("source", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "dim_sku_cost": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("cost_price", "REAL"),
        ("effective_date", "TEXT NOT NULL DEFAULT '1970-01-01'"),
        ("remark", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_sku_daily": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("sku_name", "TEXT"),
        ("transaction_amount", "REAL"),
        ("transaction_qty", "INTEGER"),
        ("transaction_order_count", "INTEGER"),
        ("transaction_customer_count", "INTEGER"),
        ("transaction_conversion_rate", "REAL"),
        ("search_impressions", "INTEGER"),
        ("search_clicks", "INTEGER"),
        ("search_ctr", "REAL"),
        ("product_views", "INTEGER"),
        ("product_visitors", "INTEGER"),
        ("add_to_cart_qty", "INTEGER"),
        ("add_to_cart_amount", "REAL"),
        ("order_amount", "REAL"),
        ("cancel_refund_amount", "REAL"),
        ("category_rank", "INTEGER"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_spu_daily": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT NOT NULL"),
        ("spu", "TEXT NOT NULL"),
        ("product_code", "TEXT"),
        ("spu_name", "TEXT"),
        ("transaction_amount", "REAL"),
        ("transaction_qty", "INTEGER"),
        ("transaction_order_count", "INTEGER"),
        ("transaction_customer_count", "INTEGER"),
        ("transaction_conversion_rate", "REAL"),
        ("search_impressions", "INTEGER"),
        ("search_clicks", "INTEGER"),
        ("search_ctr", "REAL"),
        ("product_views", "INTEGER"),
        ("product_visitors", "INTEGER"),
        ("add_to_cart_qty", "INTEGER"),
        ("add_to_cart_amount", "REAL"),
        ("order_amount", "REAL"),
        ("cancel_refund_amount", "REAL"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_search_rank_daily": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("product_info", "TEXT"),
        ("final_price", "REAL"),
        ("category_rank", "INTEGER"),
        ("impressions", "INTEGER"),
        ("impression_users", "INTEGER"),
        ("clicks", "INTEGER"),
        ("click_users", "INTEGER"),
        ("transaction_amount", "REAL"),
        ("transaction_order_count", "INTEGER"),
        ("transaction_qty", "INTEGER"),
        ("transaction_customer_count", "INTEGER"),
        ("search_ctr", "REAL"),
        ("search_conversion_rate", "REAL"),
        ("avg_order_value", "REAL"),
        ("mom_json", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_order_items": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT"),
        ("order_id", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("product_name", "TEXT"),
        ("pre_discount_amount", "REAL"),
        ("transaction_qty", "INTEGER"),
        ("discount_amount", "REAL"),
        ("order_amount", "REAL"),
        ("freight_amount", "REAL"),
        ("service_fee", "REAL"),
        ("order_time", "TEXT"),
        ("pay_time", "TEXT"),
        ("payment_method", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_cancel_order_items": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT"),
        ("order_id", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("product_name", "TEXT"),
        ("cancel_qty", "INTEGER"),
        ("cancel_amount", "REAL"),
        ("pay_time", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_refund_items": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT"),
        ("service_id", "TEXT NOT NULL"),
        ("order_id", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("product_name", "TEXT"),
        ("refund_qty", "INTEGER"),
        ("refund_amount", "REAL"),
        ("pay_time", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_aftersale_services": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("service_id", "TEXT NOT NULL"),
        ("order_id", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("customer_expectation", "TEXT"),
        ("service_status", "TEXT"),
        ("reason_level1", "TEXT"),
        ("reason_level2", "TEXT"),
        ("customer_problem", "TEXT"),
        ("return_method", "TEXT"),
        ("apply_time", "TEXT"),
        ("province", "TEXT"),
        ("city", "TEXT"),
        ("order_type", "TEXT"),
        ("warehouse_status", "TEXT"),
        ("product_name", "TEXT"),
        ("product_amount", "REAL"),
        ("product_qty", "INTEGER"),
        ("audit_result", "TEXT"),
        ("audit_time", "TEXT"),
        ("pickup_time", "TEXT"),
        ("waybill_no", "TEXT"),
        ("express_company", "TEXT"),
        ("merchant_receive_time", "TEXT"),
        ("process_result", "TEXT"),
        ("refund_amount", "REAL"),
        ("is_flash_refund", "TEXT"),
        ("service_duration", "TEXT"),
        ("raw_json", "TEXT"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "fact_sku_profit_daily": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("date", "TEXT NOT NULL"),
        ("sku", "TEXT NOT NULL"),
        ("spu", "TEXT"),
        ("product_code", "TEXT"),
        ("transaction_amount", "REAL"),
        ("refund_amount", "REAL"),
        ("net_sales_amount", "REAL"),
        ("transaction_qty", "INTEGER"),
        ("cost_amount", "REAL"),
        ("gross_profit", "REAL"),
        ("gross_margin", "REAL"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ],
    "source_files": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("file_hash", "TEXT NOT NULL"),
        ("store_id", "INTEGER"),
        ("report_type", "TEXT"),
        ("file_name", "TEXT"),
        ("file_path", "TEXT"),
        ("file_size", "INTEGER"),
        ("date_start", "TEXT"),
        ("date_end", "TEXT"),
        ("imported_at", "TEXT"),
    ],
    "import_logs": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER"),
        ("report_type", "TEXT"),
        ("file_name", "TEXT"),
        ("file_path", "TEXT"),
        ("date_start", "TEXT"),
        ("date_end", "TEXT"),
        ("total_rows", "INTEGER DEFAULT 0"),
        ("success_rows", "INTEGER DEFAULT 0"),
        ("failed_rows", "INTEGER DEFAULT 0"),
        ("skipped_rows", "INTEGER DEFAULT 0"),
        ("duplicate_rows", "INTEGER DEFAULT 0"),
        ("unmatched_sku_count", "INTEGER DEFAULT 0"),
        ("status", "TEXT"),
        ("error_message", "TEXT"),
        ("created_at", "TEXT"),
    ],
    "data_quality_unmatched_sku": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER NOT NULL"),
        ("report_type", "TEXT"),
        ("source_table", "TEXT"),
        ("date", "TEXT"),
        ("sku", "TEXT NOT NULL"),
        ("order_id", "TEXT"),
        ("service_id", "TEXT"),
        ("file_name", "TEXT"),
        ("file_path", "TEXT"),
        ("raw_json", "TEXT"),
        ("created_at", "TEXT"),
    ],
    "download_logs": [
        ("id", "INTEGER PRIMARY KEY AUTOINCREMENT"),
        ("store_id", "INTEGER"),
        ("store_name", "TEXT"),
        ("report_type", "TEXT"),
        ("report_name", "TEXT"),
        ("start_date", "TEXT"),
        ("end_date", "TEXT"),
        ("date_start", "TEXT"),
        ("date_end", "TEXT"),
        ("page_url", "TEXT"),
        ("file_name", "TEXT"),
        ("file_path", "TEXT"),
        ("download_status", "TEXT"),
        ("status", "TEXT"),
        ("download_time", "TEXT"),
        ("error_message", "TEXT"),
        ("screenshot_path", "TEXT"),
        ("created_at", "TEXT"),
    ],
}


UNIQUE_INDEXES = [
    ("ux_stores_shop_id", "stores", ["shop_id"]),
    ("ux_dim_spu", "dim_spu", ["store_id", "spu"]),
    ("ux_dim_sku", "dim_sku", ["store_id", "sku"]),
    ("ux_product_mapping", "product_mapping", ["store_id", "sku"]),
    ("ux_dim_sku_cost", "dim_sku_cost", ["store_id", "sku", "effective_date"]),
    ("ux_fact_sku_daily", "fact_sku_daily", ["store_id", "date", "sku"]),
    ("ux_fact_spu_daily", "fact_spu_daily", ["store_id", "date", "spu"]),
    ("ux_fact_search_rank_daily", "fact_search_rank_daily", ["store_id", "date", "sku"]),
    ("ux_fact_order_items", "fact_order_items", ["store_id", "order_id", "sku"]),
    ("ux_fact_cancel_order_items", "fact_cancel_order_items", ["store_id", "order_id", "sku"]),
    ("ux_fact_refund_items", "fact_refund_items", ["store_id", "service_id", "order_id", "sku"]),
    ("ux_fact_aftersale_services", "fact_aftersale_services", ["store_id", "service_id", "order_id", "sku"]),
    ("ux_fact_sku_profit_daily", "fact_sku_profit_daily", ["store_id", "date", "sku"]),
    ("ux_source_files_hash", "source_files", ["file_hash"]),
]


INDEX_SQL = [
    "CREATE INDEX IF NOT EXISTS idx_mapping_store_spu ON product_mapping(store_id, spu)",
    "CREATE INDEX IF NOT EXISTS idx_sku_daily_store_date ON fact_sku_daily(store_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_spu_daily_store_date ON fact_spu_daily(store_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_order_store_date ON fact_order_items(store_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_cancel_order_store_date ON fact_cancel_order_items(store_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_refund_store_date ON fact_refund_items(store_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_unmatched_store_sku ON data_quality_unmatched_sku(store_id, sku)",
    "CREATE INDEX IF NOT EXISTS idx_import_logs_created ON import_logs(created_at)",
]
